export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export NPM_PACKAGES="/usr/local/npm_packages"
export NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"
export PATH="$NPM_PACKAGES/bin:$PATH"
export HOME=/home/$USER
export TERM=xterm-256color
export ZSH_CACHE_DIR=$HOME/.zplug/cache
export GOPATH=$HOME/.config/go
export HISTTIMEFORMAT="%d/%m/%y %T "
